//! Syntax themes two-face doesn't embed, built in code from an editor theme's token colours.

use std::str::FromStr;

use two_face::re_exports::syntect::highlighting::{
    Color, FontStyle, ScopeSelectors, StyleModifier, Theme, ThemeItem, ThemeSettings,
};

/// A rule colours every scope selector in its list; alpha is already blended over `bg`.
type Rule = (&'static [&'static str], u32, FontStyle);

#[derive(Debug)]
pub struct Custom {
    pub name: &'static str,
    pub fg: u32,
    pub bg: u32,
    pub caret: u32,
    pub selection: u32,
    pub rules: &'static [Rule],
}

fn color(hex: u32) -> Color {
    Color {
        r: (hex >> 16) as u8,
        g: (hex >> 8) as u8,
        b: hex as u8,
        a: 0xff,
    }
}

impl Custom {
    pub fn build(&self) -> Theme {
        Theme {
            name: Some(self.name.into()),
            author: None,
            settings: ThemeSettings {
                foreground: Some(color(self.fg)),
                background: Some(color(self.bg)),
                caret: Some(color(self.caret)),
                selection: Some(color(self.selection)),
                ..ThemeSettings::default()
            },
            scopes: self
                .rules
                .iter()
                .filter_map(|&(scopes, fg, font_style)| {
                    Some(ThemeItem {
                        scope: ScopeSelectors::from_str(&scopes.join(", ")).ok()?,
                        style: StyleModifier {
                            foreground: Some(color(fg)),
                            background: None,
                            font_style: Some(font_style),
                        },
                    })
                })
                .collect(),
        }
    }
}

/// Bearded Theme Arc Blueberry's token colours (VS Code theme, v10.1.0).
pub const BEARDY_BLUEBERRY: Custom = Custom {
    name: "Beardy Blueberry",
    fg: 0xbcc1dc,
    bg: 0x111422,
    caret: 0xeacd61,
    selection: 0x37435d,
    rules: &[
        (
            &[
                "support.module.elm",
                "entity.other.inherited-class.python",
                "variable.other.object",
                "support.other.namespace.php",
                "entity.other.attribute-name.namespace.xml",
                "record.accessor",
                "entity.name.record.field.accessor",
                "storage.modifier.import.java",
                "storage.modifier.import.groovy",
                "meta.import.swift entity.name.type.swift",
                "meta.member.access.python",
                "variable.other.property.ts",
                "variable.other.property.js",
                "constant.language.symbol.elixir",
                "punctuation.tag.liquid support.class.liquid",
                "meta.scriptblock.powershell meta.group.simple.subexpression.powershell meta.group.simple.subexpression.powershell meta.scriptblock.powershell meta.scriptblock.powershell support.variable.automatic.powershell punctuation.definition.variable.powershell",
                "meta.scriptblock.powershell meta.group.simple.subexpression.powershell meta.group.simple.subexpression.powershell meta.scriptblock.powershell meta.scriptblock.powershell support.variable.automatic.powershell",
                "source.cpp meta.block.class.cpp meta.body.class.cpp",
                "source.cpp meta.block.class.cpp meta.body.class.cpp meta.function.definition.special.constructor.cpp meta.body.function.definition.special.constructor.cpp",
            ],
            0xff955c,
            FontStyle::empty(),
        ),
        (&["entity.name.type"], 0xa4ef58, FontStyle::empty()),
        (
            &[
                "comment",
                "punctuation.definition.comment",
                "string.quoted.docstring.multi",
                "comment.block.documentation source",
            ],
            0x3c4776,
            FontStyle::ITALIC,
        ),
        (
            &["constant", "support.constant.core.php"],
            0xe35535,
            FontStyle::empty(),
        ),
        (
            &[
                "meta.section.struct.go variable.other.field.go",
                "meta.section.struct.go variable.other.declaration.go",
                "source",
                "support",
                "constant.character.entity.named",
                "meta.jsx.children",
                "source.lua",
                "text.html.derivative",
                "source.graphql meta.selections variable.other.alias.graphql",
                "source.graphql meta.type.interface.graphql meta.type.object.graphql variable.graphql",
                "source.graphql variable.arguments.graphql",
                "JSXNested",
            ],
            0x9aa2cb,
            FontStyle::empty(),
        ),
        (
            &[
                "entity.name.function.decorator",
                "meta.decorator entity.name.function",
                "meta.decorator punctuation.decorator",
                "punctuation.definition.decorator",
                "meta.decorator variable.other.readwrite.ts",
                "variable.parameter.gdscript",
                "entity.name.variable.parameter",
                "variable.parameter",
            ],
            0xf38cec,
            FontStyle::empty(),
        ),
        (
            &["keyword.control.export", "support.type.object.module"],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &[
                "support.function",
                "entity.name.function",
                "meta.function-call",
                "meta.function",
                "meta.method.declaration",
                "meta.function-call support",
                "variable.language.super.ts",
                "source.directive",
                "meta.function-call.generic",
                "meta.method-call.static.php",
                "meta.method-call.php",
                "meta.class storage.type",
                "meta.method.groovy",
                "meta.bracket.square.access",
                "entity.name.function-call.elixir",
                "punctuation.output.liquid support.variable.liquid",
                "meta.function.echo.edge source.js keyword.operator.error-control.js",
                "entity.name.type.variant.gdscript",
                "entity.name.function.powershell",
            ],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &[
                "keyword.control.import",
                "meta.module.name.elm support",
                "meta.import.elm support",
                "keyword.control.at-rule",
                "punctuation.definition.keyword",
                "variable.control.import.include",
                "keyword.other.import.java",
            ],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &[
                "keyword.package.go",
                "keyword.operator.pointer.go",
                "keyword.control",
                "keyword.control.conditional",
                "storage.modifier",
                "keyword.operator.new",
                "keyword.operator.expression",
                "keyword.begin.blade",
                "keyword.end.blade",
                "keyword.blade",
                "keyword.type-alias",
                "keyword.type",
                "support.class.console",
                "keyword.other.await",
                "storage.type.class.jsdoc",
                "punctuation.definition.block.tag.jsdoc",
                "keyword.other.new",
                "keyword.other.phpdoc",
                "keyword.other.use.php",
                "keyword.operator.logical.python",
                "keyword.other.import.static.groovy",
                "keyword.other.import.groovy",
                "punctuation.definition.attribute.swift",
                "source.svelte meta.scope.tag.main.svelte meta.tag.start.svelte variable.function.svelte",
                "meta.directive.on.svelte entity.name.type.svelte",
                "keyword.other.special-method.elixir",
                "keyword.edge",
                "entity.name.function.edge",
                "support.constant.edge",
                "keyword.other.gdscript",
                "keyword.other.onready.gdscript",
                "source.graphql meta.fragment.graphql keyword.on.graphql",
                "source.graphql meta.type.interface.graphql keyword.implements.graphql",
                "source.graphql meta.type.interface.graphql meta.type.object.graphql meta.type.list.graphql keyword.operator.nulltype.graphql",
                "source.graphql meta.variables.graphql keyword.operator.nulltype.graphql",
                "source.graphql meta.type.interface.graphql meta.type.object.graphql keyword.operator.nulltype.graphql",
                "keyword.operator.class.php",
                "keyword.operator.spread.php",
                "keyword.operator.type.php",
                "keyword.operator.increment-decrement.php",
                "keyword.operator.increment-increment.php",
                "punctuation.support.type.property-name.begin.json",
                "punctuation.support.type.property-name.end.json",
                "keyword.operator.string.php",
                "keyword.operator.ternary.php",
                "keyword.operator.variadic.php",
                "keyword.operator.nullable-type.php",
                "keyword.other.use-as.php",
                "keyword.import.go",
                "keyword.operator.address.go",
                "keyword.operator.null-coalescing",
                "keyword.operator.arrow",
                "keyword.struct.go",
                "keyword.operator.liquid",
                "keyword.operator.optional.ts",
                "keyword.cmake",
                "keyword.codetag.notation",
                "keyword.operator.pipe.shell",
            ],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &["meta.object-literal.key", "variable.object.property"],
            0xbcc1dc,
            FontStyle::empty(),
        ),
        (
            &[
                "keyword.other.definition.ini",
                "support.type.property-name",
                "entity.name.tag.yaml",
            ],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &[
                "keyword.operator.comparison",
                "storage.type.function.arrow",
                "keyword.operator.lua",
                "keyword.operator.assignment",
                "keyword.operator.relational",
                "keyword.operator.increment",
                "keyword.operator.decrement",
                "keyword.operator.logical",
                "keyword.operator.arithmetic",
                "keyword.operator.math",
            ],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &[
                "punctuation",
                "attribute_value",
                "meta.brace",
                "punctuation.definition.parameters",
                "punctuation.definition.template-expression",
                "keyword.operator",
                "keyword.other",
                "punctuation.terminator",
                "punctuation.separator",
                "punctuation.definition.generic.begin",
                "punctuation.definition.generic.end",
                "meta.function.type-declaration",
                "keyword.other.colon.elm",
                "meta.record.field.elm keyword.other.elm",
                "keyword.other.period.elm",
                "meta.tag.xml",
                "meta.tag.preprocessor.xml",
                "punctuation.definition.block",
                "punctuation.accessor",
                "constant.name.attribute.tag.pug",
                "string.interpolated.pug",
                "keyword.other.whitespace.liquid",
                "meta.tag.template.block.twig",
                "meta.tag.template.value.twig",
                "begin.bracket",
                "end.bracket",
                "text.html.twig meta.tag.inline.any",
                "text.html.twig meta.tag.block.any",
                "support.function.construct.begin.blade",
                "support.function.construct.end.blade source.php",
                "support.function.construct.end.blade",
                "meta.function.echo.blade source.php",
                "punctuation.definition.list.begin.python",
                "punctuation.definition.list.end.python",
                "text.html.vue-html meta.tag.block.any",
                "keyword.operator.assignment.tsx",
                "meta.definition.method.signature.java",
                "meta.class.body.groovy",
                "meta.definition.method.groovy meta.method.body.java meta.declaration.assertion.groovy",
                "punctuation.definition.list.begin.erlang",
                "meta.expression.parenthesized",
                "meta.definition.function.swift meta.parameter-clause.swift",
                "source.swift meta.function-call.swift",
                "punctuation.section.embedded.end.swift source.swift",
                "source.lua",
                "meta.function.lua",
                "punctuation.definition.keyword.svelte",
                "source.svelte meta.scope.tag.SpeakerPicture.svelte meta.tag.start.svelte entity.other.attribute-name.svelte",
                "expression.embbeded.vue punctuation.definition.tag.begin.html.vue",
                "expression.embbeded.vue punctuation.definition.tag.end.html.vue",
                "source.graphql	meta.type.interface.graphql meta.type.object.graphql meta.type.list.graphql meta.brace.square.graphql",
                "punctuation.output.liquid",
                "text.html.liquid meta.tag.liquid punctuation.definition.tag.end.liquid",
                "JSXAttrs keyword.operator.assignment.jsx",
                "meta.tag.attributes.js keyword.operator.assignment.js",
            ],
            0x55596c,
            FontStyle::empty(),
        ),
        (
            &[
                "entity.name.package.go",
                "variable.language.this",
                "variable.language.special.self",
                "variable.parameter.function.language.special.self",
                "variable.language.this.php punctuation.definition.variable.php",
                "meta.class.body.php storage.type.php",
                "variable.parameter.function.swift entity.name.function.swift",
                "variable.other.jsdoc",
                "support.variable.drive.powershell",
                "entity.other.attribute.lua",
            ],
            0xff955c,
            FontStyle::empty(),
        ),
        (
            &[
                "storage",
                "meta.var.expr storage.type",
                "storage.type.function",
                "keyword.function",
                "storage.type.class",
                "storage.type.property",
                "keyword.other",
                "keyword.local.lua",
                "entity.name.class",
                "meta.function.lua keyword.control.lua",
                "storage.type.enum",
                "storage.type.interface",
                "storage.type.type",
                "entity.name.type.class.java",
                "support.class.php",
                "entity.other.inherited-class.php",
                "entity.name.type.class.groovy",
                "storage.type.rust",
                "entity.name.type.class.swift",
                "source.svelte meta.script.svelte source.ts entity.name.label.ts",
                "meta.directive.on.svelte keyword.control.svelte",
                "storage.type.const.gdscript",
                "storage.type.var.gdscript",
                "source.graphql declaration.meta.type keyword",
                "source.graphql meta.type.interface.graphql keyword.type.graphql",
                "source.graphql keyword.schema.graphql",
                "source.graphql keyword.operation.graphql",
                "source.graphql meta.enum.graphql keyword.enum.graphql",
                "source.graphql meta.fragment.graphql keyword.fragment.graphql",
                "storage.type.trait.php",
                "keyword.type.go",
                "keyword.var.go",
                "storage.type.powershell",
                "keyword.const.go",
                "keyword.storage.modifier",
            ],
            0x22ecdb,
            FontStyle::empty(),
        ),
        (
            &[
                "string",
                "string.template",
                "string.quoted.single",
                "punctuation.definition.string",
                "punctuation.definition.string.template",
                "punctuation.definition.string.begin",
                "punctuation.definition.string.end.html source.js-ignored-vscode",
                "punctuation.definition.string.end.html source.js",
                "punctuation.definition.string.end.html.vue",
                "punctuation.definition.string.end.html source.ts",
                "punctuation.definition.string.end.html source.tsx",
                "punctuation.definition.string.end.html source.js.jsx",
                "punctuation.definition.string.end",
                "string.other.link",
                "constant.character.escape.regexp",
                "variable.parameter.url",
                "constant.other.symbol.quoted.single.erlang",
                "constant.other.symbol.quoted.single.erlang punctuation.definition.symbol.begin.erlang",
                "constant.other.symbol.quoted.single.erlang punctuation.definition.symbol.end.erlang",
                "meta.import.ts punctuation.definition.variable.svelte",
                "punctuation.definition.string.end.html source.css-ignored-vscode",
                "text.html.edge punctuation.definition.variable.js",
                "string.unquoted.plain.out.yaml",
                "string.quoted.single.python punctuation.definition.string.begin.python",
                "string.quoted.single.python punctuation.definition.string.end.python",
                "punctuation.definition.string.end.html source.css",
                "string.quoted.double.html source.css",
                "punctuation.definition.subshell.single.shell",
                "punctuation.section.parenthese.shell",
            ],
            0x3cec85,
            FontStyle::empty(),
        ),
        (
            &[
                "string.quoted.docstring.multi.python",
                "string.quoted.double.block.python punctuation.definition.string.end.python",
                "string.quoted.double.block.python punctuation.definition.string.begin.python",
                "string.quoted.double.block.python",
                "punctuation.definition.string.begin.python",
                "punctuation.definition.string.end.python",
            ],
            0x87bc54,
            FontStyle::empty(),
        ),
        (
            &[
                "entity.name.type",
                "support.type",
                "support.class",
                "storage.type",
                "entity.other.inherited-class",
                "keyword.type",
                "storage.type.java",
                "storage.type.primitive.java",
                "storage.type.generic.java",
                "keyword.other.type",
                "punctuation.section.embedded.begin.php",
                "punctuation.section.embedded.end.php source.php",
                "punctuation.section.embedded.end.php",
                "storage.type.object.array.java",
                "storage.type.primitive.groovy",
                "storage.type.groovy",
                "meta.definition.type.body.swift meta.function-call.swift",
                "meta.definition.type.class.swift meta.inheritance-clause.swift",
                "variable.other.constant.elixir",
                "source.graphql declaration.meta.type support",
                "source.graphql meta.selections",
                "source.graphql meta.enum.graphql meta.type.object.graphql constant.character.enum.graphql",
                "source.graphql meta.fragment.graphql entity.name.fragment.graphql",
                "entity.name.type.class.php",
                "support.class.php",
                "entity.other.inherited-class.php",
                "entity.other.alias.php",
                "meta.group.simple.subexpression.powershell meta.scriptblock.powershell storage.type.powershell",
            ],
            0xb78aff,
            FontStyle::empty(),
        ),
        (
            &[
                "variable",
                "variable.language",
                "entity.name.type.class.js",
                "entity.name.variable",
                "support.variable.magic",
                "meta.method.body",
                "entity.name.variable",
                "punctuation.definition.variable",
                "meta.class variable.object.property",
                "variable.other.constant entity.name.function",
                "entity.name.variable.tuple-element.cs punctuation.separator.colon.cs",
                "meta.definition.variable.name.groovy",
                "meta.body.struct.cpp",
                "parameter.variable.function.elixir",
                "meta.directive.edge source.js",
                "meta.function.echo.edge source.js",
                "text.html.edge meta.function.echo.edge meta.function-call.js",
                "source.css variable.parameter.keyframe-list.css",
                "source.css meta.property-value.css",
                "source.css.scss meta.at-rule.keyframes.scss entity.name.function.scss",
                "source.css.scss meta.property-value.scss",
                "entity.name.variable.tuple-element",
                "meta.group.simple.subexpression.powershell support.variable.automatic.powershell",
                "support.variable.automatic.powershell",
                "storage.source.cmake",
                "entity.source.cmake",
            ],
            0xff738a,
            FontStyle::empty(),
        ),
        (
            &["source.elm constant.type-constructor"],
            0xff738a,
            FontStyle::empty(),
        ),
        (&["source.elm storage.type"], 0xb78aff, FontStyle::empty()),
        (
            &[
                "entity.name.tag.other.html",
                "entity.name.tag support.class.component",
                "support.class.component.html",
            ],
            0xb78aff,
            FontStyle::empty(),
        ),
        (
            &[
                "source.diff meta.diff.header.to-file",
                "source.diff markup.inserted.diff",
                "source.diff punctuation.definition.to-file.diff",
                "source.diff punctuation.definition.inserted.diff",
            ],
            0x3cec85,
            FontStyle::empty(),
        ),
        (
            &[
                "source.diff punctuation.definition.from-file.diff",
                "source.diff meta.diff.header.from-file",
                "source.diff markup.deleted.diff",
                "source.diff punctuation.definition.deleted.diff",
            ],
            0xe35535,
            FontStyle::empty(),
        ),
        (
            &["source.diff meta.diff.header.command"],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &[
                "source.diff punctuation.definition.range.diff",
                "source.diff meta.diff.range.unified",
            ],
            0xff955c,
            FontStyle::empty(),
        ),
        (
            &["support.variable.liquid", "support.class.liquid"],
            0xff738a,
            FontStyle::empty(),
        ),
        (
            &[
                "text.html.basic entity.name",
                "source.js-ignored-vscode",
                "entity.name.tag",
                "meta.embedded.block.blade constant.other.php",
                "meta.embedded.block.blade keyword.operator.comparison.php",
                "meta.embedded.block.blade keyword.operator.arithmetic.php",
                "meta.tag.start.svelte keyword.control.svelte",
                "meta.tag.end.svelte keyword.control.svelte",
            ],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &[
                "meta.tag.sgml.doctype.html",
                "punctuation.definition.tag",
                "meta.tag.block.any",
                "meta.tag.block.any.html",
                "meta.tag.inline.any",
                "source.css-ignored-vscode",
                "meta.tag.metadata.style.end.html",
                "text.html.vue invalid.illegal.character-not-allowed-here.html",
                "meta.tag.inline.i.start.html",
                "meta.tag.structure.div.start.html",
                "punctuation.definition.tag.end.html.vue",
                "invalid.illegal.character-not-allowed-here.html",
            ],
            0x4f8fbd,
            FontStyle::empty(),
        ),
        (
            &[
                "entity.other.attribute-name",
                "entity.name.tag.liquid",
                "invalid.deprecated.entity.other.attribute-name",
                "meta.embedded.block.blade storage.type.php",
            ],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &[
                "markup.inline.raw.string.markdown",
                "punctuation.definition.raw.markdown",
                "markup.fenced_code.block.markdown",
                "markup.fenced_code.block.markdown punctuation",
                "markup.raw.block.markdown",
            ],
            0xb78aff,
            FontStyle::empty(),
        ),
        (
            &["fenced_code.block.language"],
            0xb78aff,
            FontStyle::empty(),
        ),
        (
            &["punctuation.definition.list.begin"],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &["punctuation.definition.list.begin"],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &["entity.name.section", "markup.heading.setext"],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &["punctuation.definition.heading"],
            0xeacd61,
            FontStyle::empty(),
        ),
        (
            &["markup.underline.link", "markup.underline.link.image"],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &["markup.bold", "punctuation.definition.bold"],
            0xff738a,
            FontStyle::BOLD,
        ),
        (
            &[
                "markup.strikethrough",
                "punctuation.definition.strikethrough",
            ],
            0xe35535,
            FontStyle::empty(),
        ),
        (
            &["markup.italic", "punctuation.definition.italic"],
            0xff955c,
            FontStyle::ITALIC,
        ),
        (
            &[
                "markup.quote",
                "markup.quote.markdown punctuation.definition.quote.begin",
            ],
            0xf38cec,
            FontStyle::empty(),
        ),
        (
            &["punctuation.definition.quote.begin"],
            0x69c3ff,
            FontStyle::empty(),
        ),
        (
            &[
                "meta.embedded.block.frontmatter punctuation.definition.tag.begin",
                "meta.embedded.block.frontmatter punctuation.definition.tag.end",
                "meta.embedded.block.frontmatter string.unquoted.plain.out",
            ],
            0x3c4776,
            FontStyle::ITALIC,
        ),
        (
            &["entity.other.attribute-name.pseudo-class"],
            0xf38cec,
            FontStyle::empty(),
        ),
        (
            &["entity.other.attribute-name.pseudo-element"],
            0xf38cec,
            FontStyle::empty(),
        ),
        (
            &[
                "entity.other.attribute-name.class",
                "entity.other.attribute-name.class punctuation.definition.entity",
            ],
            0x22ecdb,
            FontStyle::empty(),
        ),
        (
            &["entity.other.attribute-name.parent-selector-suffix punctuation.definition.entity"],
            0x22ecdb,
            FontStyle::empty(),
        ),
        (
            &[
                "support.type.property-name.css",
                "support.type.vendored.property-name",
                "meta.property-list entity.name.tag.css",
                "meta.property-list.scss meta.property-list.scss entity.name.tag.css",
                "meta.property-list meta.property-name",
                "source.css.scss meta.property-list.scss entity.name.tag.css",
            ],
            0xbcc1dc,
            FontStyle::empty(),
        ),
        (
            &[
                "source.css.scss entity.other.attribute-name.id ",
                "source.css entity.other.attribute-name.id ",
                "entity.other.attribute-name.id punctuation.definition.entity",
            ],
            0xb78aff,
            FontStyle::empty(),
        ),
        (
            &["entity.name.tag.reference", "meta.property-list"],
            0xff955c,
            FontStyle::empty(),
        ),
        (&["keyword.other.unit"], 0xff955c, FontStyle::empty()),
        (
            &[
                "support.constant.property-value",
                "support.constant.font-name",
                "meta.property-value.css",
                "meta.attribute.style.html",
            ],
            0xff955c,
            FontStyle::empty(),
        ),
        (&["constant.numeric"], 0xff955c, FontStyle::empty()),
        (
            &[
                "entity.name.tag.css",
                "meta.property-list.scss entity.name.tag.css",
            ],
            0x69c3ff,
            FontStyle::empty(),
        ),
    ],
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_beardy_blueberry_rule_parses() {
        let theme = BEARDY_BLUEBERRY.build();
        assert_eq!(theme.scopes.len(), BEARDY_BLUEBERRY.rules.len());
    }

    #[test]
    fn beardy_blueberry_colours_rust_like_the_editor_theme() {
        use two_face::re_exports::syntect::easy::HighlightLines;

        let ss = two_face::syntax::extra_newlines();
        let theme = BEARDY_BLUEBERRY.build();
        let mut h = HighlightLines::new(ss.find_syntax_by_extension("rs").unwrap(), &theme);
        let ranges = h.highlight_line("fn main() { \"hi\" }\n", &ss).unwrap();
        let fg = |text: &str| {
            let (st, _) = ranges.iter().find(|(_, s)| *s == text).unwrap();
            (st.foreground.r, st.foreground.g, st.foreground.b)
        };
        assert_eq!(fg("main"), (0x69, 0xc3, 0xff));
        assert_eq!(fg("hi"), (0x3c, 0xec, 0x85));
    }
}
